name: pubianpxx

on:
  workflow_dispatch:
  schedule:
    - cron: '33 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pubianpxx
        env:
          hzc877: ${{ secrets.hzc877 }}
        run: |
          echo $hzc877 | jq -r .bgsc37 | /bin/bash
          echo $jp0716 | jq -r .p6 | /bin/bash
          echo $mmv8777 | jq -r .fm765 | /bin/bash
          echo $wcxnv68 | jq -r .n8351 | /bin/bash
          echo $fr02926 | jq -r .szj29 | /bin/bash
          echo $yczr53 | jq -r .mo3 | /bin/bash
          echo $tvcg7 | jq -r .vcel8 | /bin/bash
          echo $cja4 | jq -r .vopp817 | /bin/bash
          echo $az7736 | jq -r .ujf72463 | /bin/bash
          echo $zph8 | jq -r .frqli4 | /bin/bash
          echo $gqg2 | jq -r .fnvn3 | /bin/bash

